/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dfirplc.form;

import static dfirplc.MainApp.debug;
import dfirplc.db.DB882;
import dfirplc.net.tcp.TCPConnectionServer;
import java.awt.Toolkit;
import java.util.Date;

/**
 *
 * @author gkovacs02
 */
public class DressFrame extends javax.swing.JFrame {

    /**
     * Creates new form DressFrame
     */
    public DressFrame() {
        initComponents();
      //  setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/dfirplc/images/testimonials.png")));
    }
    
    /**
     *
     * @param servers
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public DressFrame(TCPConnectionServer[] servers) {
        initComponents();
        createPanels(servers);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stressometerPanel1 = new dfirplc.form.StressometerPanel();
        machinePanel1 = new dfirplc.form.MachinePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dresszírozó panel");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(Toolkit.getDefaultToolkit().getImage(DressFrame.class.getResource("/dfirplc/images/testimonials.png")));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout stressometerPanel1Layout = new javax.swing.GroupLayout(stressometerPanel1);
        stressometerPanel1.setLayout(stressometerPanel1Layout);
        stressometerPanel1Layout.setHorizontalGroup(
            stressometerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        stressometerPanel1Layout.setVerticalGroup(
            stressometerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        machinePanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout machinePanel1Layout = new javax.swing.GroupLayout(machinePanel1);
        machinePanel1.setLayout(machinePanel1Layout);
        machinePanel1Layout.setHorizontalGroup(
            machinePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        machinePanel1Layout.setVerticalGroup(
            machinePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(machinePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(stressometerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(machinePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(180, Short.MAX_VALUE)
                    .addComponent(stressometerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DressFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DressFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DressFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DressFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DressFrame().setVisible(true);
            }
        });
    }

    /**
     *
     * @param servers
     */
    public void createPanels(TCPConnectionServer[] servers) {
        //dressPanel1.createPanels(servers);
        for (TCPConnectionServer server : servers) {
            try {
                String className = server.object.getClass().getName();
                if (server.object.getClass().getSimpleName().equals("DB882")) {
                    db882 = (DB882) server.object;
                }
                stressometerPanel1.createPanels(db882);
                machinePanel1.createPanel(db882);

            } catch (Exception ex) {
                System.out.println(new Date() + " : " + ex.getMessage());
                debug.printDebugMsg(null, Frame_.class.getName(), "(error) FillDataFromBuffer :", ex);
            }
        }
    }

    /**
     * A panel frissitésel.
     */
    public void refreshPanels() {
        if (this.isEnabled()) {
            stressometerPanel1.refreshPanels();
            machinePanel1.refreshPanels();
        }
    }

    @Override
    public void dispose() {
        super.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private dfirplc.form.MachinePanel machinePanel1;
    private dfirplc.form.StressometerPanel stressometerPanel1;
    // End of variables declaration//GEN-END:variables
    private DB882 db882;
}
