/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dfirplc.form;

import dfirplc.MainApp;
import dfirplc.net.tcp.TCPConnectionServer;
import dfirplc.tools.S7String;
import java.lang.reflect.Field;
import java.util.Date;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;

/**
 *
 * @author gabesz
 */
public class Frame_ extends javax.swing.JFrame {

    /**
     * Creates new form Frame_
     */
    public Frame_() {
        initComponents();
        this.setExtendedState(Frame_.MAXIMIZED_BOTH);
    }

    /**
     *
     * @param servers
     */
    public void createPanels(TCPConnectionServer[] servers) {
        for (TCPConnectionServer server : servers) {
            try {
                String className = server.object.getClass().getName();
                this.jTabbedPane1.addTab(className, new Table(server.object));
            } catch (Exception ex) {
                System.out.println(new Date() + " : " + ex.getMessage());
                MainApp.debug.printDebugMsg(null,Frame_.class.getName(),"(error) FillDataFromBuffer :" ,ex);
            }
        }
    }

    /**
     *
     * @param servers
     */
    public void refreshPanels(TCPConnectionServer[] servers) {

        Table table = (Table) jTabbedPane1.getSelectedComponent();
        JScrollPane jScrollPane = (JScrollPane) table.getComponent(0);
        JTable jTable = (JTable) jScrollPane.getViewport().getComponents()[0];
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        String className = jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex());
        for (int ind = 0; ind < servers.length; ind++) {
            Object object = servers[ind].object;
            String n = object.getClass().getName();
            if (object.getClass().getName().equals(className)) {
                Field[] fields = object.getClass().getDeclaredFields();
                String name;
                for (int index = 0; index < fields.length; index++) {
                    try {
                        name = fields[index].getType().getName();
                        String[] s = name.split("\\.");
                        if (s.length > 0) {
                            int i = s.length - 1;
                            name = s[i];
                        }
                        model.setValueAt(fields[index].getName(), index, 0);
                        model.setValueAt(name, index, 1);
                        if (fields[index].getType().getName().equals(S7String.class.getPackage().getName() + "." + "S7String")) {
                            S7String s7String = (S7String) fields[index].get(object);
                            model.setValueAt(s7String.getMyString(), index, 2);
                        } else {
                            model.setValueAt(fields[index].get(object), index, 2);
                        }

                    } catch (Exception ex) {
                        System.out.println(new Date() + " : " + ex.getMessage());
                        MainApp.debug.printDebugMsg(null,Frame_.class.getName(),"(error) Frame_ :",ex);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PLC Üzenetek");
        setIconImage(Toolkit.getDefaultToolkit().getImage(Frame_.class.getResource("/dfirplc/images/testimonials.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return jTabbedPane
     */
    public JTabbedPane getTabbedPane() {
        return this.jTabbedPane1;
    }
    
    @Override
    public void dispose() {
        super.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
