/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Table.java
 *
 * Created on Feb 26, 2014, 10:43:53 AM
 */
package dfirplc.form;

import dfirplc.MainApp;
import static dfirplc.MainApp.debug;
import dfirplc.tools.S7String;
import java.lang.reflect.Field;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabesz
 */
public class Table extends javax.swing.JPanel{
    
    /**
     * Creates new form Table
     * @param object 
     */
    public Table(Object object) {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Field[] fields = object.getClass().getDeclaredFields();
        String name;
        for (Field field : fields) {
            try {
                name = field.getType().getName();
                String[] s = name.split("\\.");
                if (s.length > 0) {
                    int i = s.length - 1;
                    name = s[i];
                }
                if (field.getType().getName().equals(S7String.class.getPackage().getName()+"."+"S7String")) {
                    S7String s7String = (S7String) field.get(object);
                    model.addRow(new Object[]{field.getName(), name, s7String.getMyString()});
                } else {
                    model.addRow(new Object[]{field.getName(), name, field.get(object)});
                }
            } catch (IllegalArgumentException | IllegalAccessException ex) {
                System.err.println(new Date() +" : " + ex.getMessage());
               debug.printDebugMsg(null,Table.class.getName(),"(error) Table :",ex);
            }
        }
         
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Név", "Tipus", "Érték"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("dfirplc/form/Bundle"); // NOI18N
        jTable1.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("Table.jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("Table.jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("Table.jTable1.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
